[2019-05-31 04:48:18 -0400] [8534] [INFO] Starting gunicorn 19.9.0
[2019-05-31 04:48:18 -0400] [8534] [INFO] Listening at: http://127.0.0.1:8000 (8534)
[2019-05-31 04:48:18 -0400] [8534] [INFO] Using worker: sync
[2019-05-31 04:48:18 -0400] [8537] [INFO] Booting worker with pid: 8537
[2019-05-31 04:48:18 -0400] [8537] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ziyuewanfeng/sites/blog/blogProjectEnv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ziyuewanfeng/sites/blog/blogProjectEnv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/ziyuewanfeng/sites/blog/blogProjectEnv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ziyuewanfeng/sites/blog/blogProjectEnv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ziyuewanfeng/sites/blog/blogProjectEnv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ziyuewanfeng/sites/blog/blogProjectEnv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ziyuewanfeng/sites/blog/blogProjectEnv/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'mypoject'
[2019-05-31 04:48:18 -0400] [8537] [INFO] Worker exiting (pid: 8537)
[2019-05-31 04:48:18 -0400] [8534] [INFO] Shutting down: Master
[2019-05-31 04:48:18 -0400] [8534] [INFO] Reason: Worker failed to boot.
